/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:6aa91918-76d5-49fa-b1ca-fce6a7961347",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_25FRLz9bg",
    "aws_user_pools_web_client_id": "7t5l2as3oga7fanvd7s080gdmc",
    "oauth": {}
};


export default awsmobile;
